### ISSUE TITLE
Smarter detection of path changes

### ISSUE THREAD

**Issue by petkostas** [Tufin/oasdiff#117]
Recently we detected that one of our OAS files had the path prefix included in the path operations instead of the server URL, we moved to fix this, by stripping and moving the prefix to the server.
OAS Diff doing its job, detected those as breaking changes, something that would be true if we really changed the entire path of the operation.
But since this was only moved to the server the true path was not truly modified in a breaking way.

**Describe the solution you'd like**
Compare the entire URL of the operation (including the server)

**Additional context**
Example of breaking change:
```
==========================================================================
==                            API CHANGE LOG                            ==
==========================================================================
                               Test                               
--------------------------------------------------------------------------
--                              What's New                              --
--------------------------------------------------------------------------
- GET    /test/
- GET    /test/{id}
--------------------------------------------------------------------------
--                            What's Deleted                            --
--------------------------------------------------------------------------
- GET    /api/v2/test/
- GET    /api/v2/test/{id}
--------------------------------------------------------------------------
--                                Result                                --
--------------------------------------------------------------------------
                 API changes broke backward compatibility                 
--------------------------------------------------------------------------
```

**Comment by reuvenharrison** [comment]
Hi Kostas.
oasdiff supports something similar with the -prefix flag:
```
-prefix string
    	if provided, paths in base spec will be compared with 'prefix'+paths in revision spec
```

Except, it seems like you need a new flag like this:
```
-strip-prefix string
    	if provided, 'prefix'+paths in base spec will be compared with paths in revision spec
```

Please try running your diff with base and revision specs exchanged:
```
oasdiff -prefix "/api/v2" -base <your **revised** spec> -revision <your **original** spec>
```
If it works as expected, I will add the -strip-prefix flag.

**Comment by petkostas** [comment]
Hey @reuvenharrison many thanks for the prompt reply! I will test this tomorrow and get back to you asap! :)

**Comment by reuvenharrison** [comment]
Hi Kostas,
I'd like to close this issue.
Please let me know if you have any feedback.

**Comment by petkostas** [comment]
@reuvenharrison sorry for the delay, just overwhelmed a bit with things in work and didn't have the time, I will try to make a test case tomorrow and get back to you in the morning!

**Comment by petkostas** [comment]
@reuvenharrison I can acknowledge that the suggested proposal with the `-prefix` works, the `-strip-prefix` would be a nice addition as well,

**Comment by reuvenharrison** [comment]
See https://github.com/Tufin/oasdiff#path-prefix-modification
