### ISSUE TITLE
String formating problem in [request-parameter-default-value-changed] 

### ISSUE THREAD

**Issue by vsarakhan** [Tufin/oasdiff#250]
Good afternoon. I noticed an error in the formation of the request-parameter-default-value-changed error message:
`[request-parameter-default-value-changed] error at spec_compatibility/openApiSpec.yaml, in API GET /accounting/products for the 'query' request parameter 'take', default value was changed from '%!s(<nil>)' to '100.00'`

**Comment by reuvenharrison** [comment]
Hi @vsarakhan 
I fixed the problem and now the code will produce:
`default value was changed from 'undefined' to '100.00'`

Question:
Would you consider this a breaking-change?
As far as I understand, if the default value of a request parameter was undefined, then changing it to any specific value is not breaking.
What do you think?

**Comment by vsarakhan** [comment]
Hi, @reuvenharrison! Thank you so much for the quick bug fix. 
I think this is a breaking change, since the API client could not set the value of an optional parameter, thinking that this variable does not affect the final output in any way, and now this variable will have a default value. For example, the request had a filtering status property (enum), but the user did not specify it and received all records in the output, and now this parameter is the default and the output of the result has changed.
